# Generated by Django 5.1.1 on 2024-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('url_video', models.URLField(default='https://www.youtube.com/watch?v=HgKjhFEguy')),
                ('upline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BonoAPagar',
            fields=[
                ('id_bono', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BonoCpa',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BonoCpaIndirecto',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('idAfiliado', models.CharField(max_length=50)),
                ('userTelegram', models.CharField(max_length=200)),
                ('idCliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpa_a_pagar',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_monto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('spread_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('spread_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_cpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('cpa', models.IntegerField(default=0)),
                ('cpaIndirecto', models.IntegerField(default=0)),
                ('level_bono_directo', models.IntegerField(default=0)),
                ('level_bono_indirecto', models.IntegerField(default=0)),
                ('retiros', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('have_bono', models.BooleanField(default=False)),
                ('have_bono_indirecto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_cpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(null=True)),
                ('fpa', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('fecha_calif', models.DateField(null=True)),
                ('country', models.CharField(max_length=30)),
                ('posicion_cuenta', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('primer_deposito', models.FloatField(default=0)),
                ('fecha_primer_deposito', models.DateField(null=True)),
                ('neto_deposito', models.FloatField(default=0)),
                ('numeros_depositos', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_cpa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(null=True)),
                ('monto_real', models.FloatField()),
                ('monto', models.FloatField()),
                ('cpa', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_ganancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('deal_id', models.CharField(max_length=100)),
                ('fpa', models.CharField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('partner_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_operacion', models.DateField(null=True)),
                ('position', models.CharField(max_length=100)),
                ('spreak_direct', models.FloatField(default=0)),
                ('spreak_indirecto', models.FloatField(default=0)),
                ('spreak_socio', models.FloatField(default=0)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relation_fpa_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(null=True)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_verificacion', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('idSpread', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('spread', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpreadIndirecto',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa_child', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
