# Generated by Django 4.2.1 on 2024-09-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpaIndirecto',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa_child', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
