# Generated by Django 4.2.1 on 2024-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoAPagar',
            fields=[
                ('id_bono', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BonoCpa',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BonoCpaIndirecto',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_monto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('spread_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('spread_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_cpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('cpa', models.IntegerField(default=0)),
                ('cpaIndirecto', models.IntegerField(default=0)),
                ('level_bono_directo', models.IntegerField(default=0)),
                ('level_bono_indirecto', models.IntegerField(default=0)),
                ('retiros', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('have_bono', models.BooleanField(default=False)),
                ('have_bono_indirecto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_cpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('idSpread', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('spread', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField()),
            ],
        ),
    ]
