# Generated by Django 3.2.18 on 2024-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0002_bonoapagar_bonocpa_bonocpaindirecto_cpa_cuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('url_video', models.URLField(default='https://www.youtube.com/watch?v=HgKjhFEguy')),
                ('upline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('idAfiliado', models.CharField(max_length=50)),
                ('userTelegram', models.CharField(max_length=200)),
                ('idCliente', models.CharField(max_length=50)),
            ],
        ),
    ]
