# Generated by Django 4.2.1 on 2024-09-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0002_cpaindirecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliado',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
