# Generated by Django 4.2.1 on 2024-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0003_delete_afiliado_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorealizado',
            name='commission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='deal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='id_db',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='id_pago',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='tipo_pago',
            field=models.CharField(choices=[('cpa', 'Comisión CPA'), ('directa', 'Ganancia Directa'), ('indirecta', 'Ganancia Indirecta'), ('bono_directo', 'Bono Directo'), ('bono_indirecto', 'Bono Indirecto')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
