# Generated by Django 4.2.1 on 2024-09-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0004_pagorealizado_commission_id_pagorealizado_deal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorealizado',
            name='desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagorealizado',
            name='hasta',
            field=models.DateField(null=True),
        ),
    ]
