# Generated by Django 4.2.1 on 2024-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0005_pagorealizado_desde_pagorealizado_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono_directo_pagado',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bono_indirecto_pagado',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpa_directo_pagado',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cpa_indirecto_pagado',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa_child', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spread_directo_pagado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('deal_id', models.CharField(max_length=100)),
                ('fpa', models.CharField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('partner_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_operacion', models.DateField(null=True)),
                ('position', models.CharField(max_length=100)),
                ('spreak_direct', models.FloatField(default=0)),
                ('spreak_indirecto', models.FloatField(default=0)),
                ('spreak_socio', models.FloatField(default=0)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spread_indirecto_pagado',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa_child', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='PagoRealizado',
        ),
    ]
