# Generated by Django 4.2.1 on 2024-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0006_bono_directo_pagado_bono_indirecto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='commission_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='commission_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
