# Generated by Django 4.2.1 on 2024-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0007_cpa_directo_pagado_commission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono_directo_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bono_directo_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bono_indirecto_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bono_indirecto_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spread_directo_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spread_directo_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spread_directo_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spread_indirecto_pagado',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spread_indirecto_pagado',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
    ]
