# Generated by Django 4.2.1 on 2024-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0008_bono_directo_pagado_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='tipo_comision',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='tipo_comision',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
