# Generated by Django 4.2.1 on 2024-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0009_cpa_directo_pagado_tipo_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='client',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
