# Generated by Django 4.2.1 on 2024-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0010_cpa_indirecto_pagado_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bono_directo_pagado',
            old_name='fecha_creacion',
            new_name='fecha_pagado',
        ),
        migrations.RenameField(
            model_name='bono_indirecto_pagado',
            old_name='fecha_creacion',
            new_name='fecha_pagado',
        ),
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spread_directo_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spread_indirecto_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpa_directo_pagado',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cpa_indirecto_pagado',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='spread_indirecto_pagado',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
