# Generated by Django 4.2.1 on 2024-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0011_rename_fecha_creacion_bono_directo_pagado_fecha_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spread_indirecto_pagado',
            name='id_spread_indirecto',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
