# Generated by Django 4.2.1 on 2024-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0012_spread_indirecto_pagado_id_spread_indirecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono_directo_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bono_indirecto_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
