# Generated by Django 4.2.1 on 2024-09-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0013_bono_directo_pagado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono_directo_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bono_directo_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bono_indirecto_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bono_indirecto_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cpa_directo_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cpa_indirecto_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spread_directo_pagado',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spread_directo_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spread_indirecto_pagado',
            name='fecha_pagado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
