# Generated by Django 4.2.1 on 2024-10-02 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0014_alter_bono_directo_pagado_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_ganancia_pagadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa', models.CharField(max_length=50, null=True)),
                ('client', models.CharField(max_length=50, null=True)),
                ('fecha_desde', models.DateField(null=True)),
                ('fecha_hasta', models.DateField(null=True)),
                ('monto_total', models.FloatField()),
                ('monto_spread_directo', models.FloatField()),
                ('monto_spread_indirecto', models.FloatField()),
                ('monto_cpa_directo', models.FloatField()),
                ('monto_cpa_indirecto', models.FloatField()),
                ('monto_bono_directo', models.FloatField()),
                ('monto_bono_indirecto', models.FloatField()),
                ('nivel_bono_directo', models.IntegerField()),
                ('nivel_bono_indirecto', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bono_directo_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bono_directo_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bono_indirecto_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bono_indirecto_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpa_directo_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cpa_directo_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpa_indirecto_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cpa_indirecto_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spread_directo_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spread_directo_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spread_indirecto_pagado',
            name='registros_ganancia_pagadas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spread_indirecto_pagado', to='skilling.registros_ganancia_pagadas'),
            preserve_default=False,
        ),
    ]
