# Generated by Django 4.2.1 on 2024-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0015_registros_ganancia_pagadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros_ganancia_pagadas',
            name='client',
        ),
        migrations.AlterField(
            model_name='relation_fpa_client',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relation_fpa_client',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relation_fpa_client',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation_fpa_client',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
