# Generated by Django 4.2.1 on 2024-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilling', '0016_remove_registros_ganancia_pagadas_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_verificacion', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
