# Generated by Django 4.2.4 on 2023-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(null=True)),
                ('fpa', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100, null=True)),
                ('fecha_calif', models.DateField(null=True)),
                ('country', models.CharField(max_length=30)),
                ('posicion_cuenta', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('primer_deposito', models.FloatField(default=0)),
                ('fecha_primer_deposito', models.DateField(null=True)),
                ('neto_deposito', models.FloatField(default=0)),
                ('numeros_depositos', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0)),
            ],
        ),
    ]
