# Generated by Django 4.2.4 on 2023-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_registro_archivo_fpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_cpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(null=True)),
                ('monto', models.FloatField()),
                ('cpa', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
            ],
        ),
    ]
