# Generated by Django 4.2.4 on 2023-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registros_cpa_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_ganancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partner_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skilling_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skilling_markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skilling_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_last_trade', models.DateField()),
                ('fecha_first_trade', models.DateField()),
                ('closed_trade_count', models.PositiveIntegerField()),
                ('customer_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawals', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
