# Generated by Django 4.2.4 on 2023-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registros_ganancias_fpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_ganancias',
            name='deposito',
            field=models.CharField(max_length=50),
        ),
    ]
