# Generated by Django 4.2.4 on 2023-08-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_registros_ganancias_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_ganancias',
            name='withdrawals',
            field=models.CharField(max_length=50),
        ),
    ]
