# Generated by Django 4.2.4 on 2023-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_registros_ganancias_withdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_ganancias',
            name='fecha_first_trade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registros_ganancias',
            name='fecha_last_trade',
            field=models.DateField(null=True),
        ),
    ]
