# Generated by Django 4.2.4 on 2023-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_registros_ganancias_fecha_first_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_ganancias',
            name='fpa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
