# Generated by Django 4.2.4 on 2023-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_registros_ganancias_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros_ganancias',
            name='spreak_direct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registros_ganancias',
            name='spreak_indirecto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registros_ganancias',
            name='spreak_socio',
            field=models.FloatField(default=0),
        ),
    ]
