# Generated by Django 4.2.4 on 2023-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_registros_ganancias_monto_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros_ganancias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
