# Generated by Django 4.2.4 on 2023-08-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_registros_ganancias_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpa_a_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('monto', models.FloatField()),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='registros_cpa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
