# Generated by Django 4.2.4 on 2023-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cpa_a_pagar_alter_registros_cpa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros_ganancias',
            old_name='fecha_first_trade',
            new_name='fecha_operacion',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='closed_trade_count',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='country',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='customer_pnl',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='deposito_neto',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='fecha_last_trade',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='skilling_markup',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='volumen',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='withdrawals',
        ),
        migrations.AddField(
            model_name='registros_ganancias',
            name='deal_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registros_ganancias',
            name='position',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registros_ganancias',
            name='symbol',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
