# Generated by Django 4.2.1 on 2023-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_cpa_a_pagar_id_alter_spreadindirecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros_cpa',
            name='monto_real',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
