# Generated by Django 4.2.1 on 2023-09-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_registros_cpa_monto_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='skilling_commission',
        ),
        migrations.RemoveField(
            model_name='registros_ganancias',
            name='skilling_earning',
        ),
    ]
