# Generated by Django 4.2.1 on 2024-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_registros_ganancias_skilling_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadindirecto',
            name='fecha_operacion',
            field=models.DateField(null=True),
        ),
    ]
