# Generated by Django 4.2.1 on 2024-01-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_registros_ganancias_skilling_commission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpa_a_pagar',
        ),
        migrations.DeleteModel(
            name='registro_archivo',
        ),
        migrations.DeleteModel(
            name='Registros_cpa',
        ),
        migrations.DeleteModel(
            name='Registros_ganancias',
        ),
        migrations.DeleteModel(
            name='Relation_fpa_client',
        ),
        migrations.DeleteModel(
            name='SpreadIndirecto',
        ),
    ]
