# Generated by Django 4.2.1 on 2024-01-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_spreadindirecto_fecha_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadindirecto',
            name='fecha_operacion',
        ),
    ]
