# Generated by Django 4.2 on 2023-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificar',
            name='deposito',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
