# Generated by Django 4.2.1 on 2024-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpa_a_pagar',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(null=True)),
                ('fpa', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('fecha_calif', models.DateField(null=True)),
                ('country', models.CharField(max_length=30)),
                ('posicion_cuenta', models.FloatField(default=0)),
                ('volumen', models.FloatField(default=0)),
                ('primer_deposito', models.FloatField(default=0)),
                ('fecha_primer_deposito', models.DateField(null=True)),
                ('neto_deposito', models.FloatField(default=0)),
                ('numeros_depositos', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_cpa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(null=True)),
                ('monto_real', models.FloatField()),
                ('monto', models.FloatField()),
                ('cpa', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_ganancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('deal_id', models.CharField(max_length=100)),
                ('fpa', models.CharField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('partner_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_operacion', models.DateField(null=True)),
                ('position', models.CharField(max_length=100)),
                ('spreak_direct', models.FloatField(default=0)),
                ('spreak_indirecto', models.FloatField(default=0)),
                ('spreak_socio', models.FloatField(default=0)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relation_fpa_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(null=True)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_verificacion', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadIndirecto',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fpa_child', models.CharField(max_length=50)),
                ('fpa', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
