# Generated by Django 4.2 on 2023-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.TextField(max_length=50)),
                ('nombre', models.TextField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
