# Generated by Django 3.2.18 on 2024-09-05 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='tipoUrl',
        ),
        migrations.RemoveField(
            model_name='url',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TipoUrl',
        ),
        migrations.AddField(
            model_name='usuariourl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.url'),
        ),
        migrations.AddField(
            model_name='usuariourl',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='urls_asignados',
            field=models.ManyToManyField(related_name='usuario_urls', through='usuarios.UsuarioUrl', to='usuarios.Url'),
        ),
    ]
