# Generated by Django 4.2 on 2023-07-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_afiliadoid_usuario_link_usuario_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='monto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='retiros',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
