# Generated by Django 5.1.1 on 2024-09-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20240905_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='urls_asignados',
        ),
        migrations.DeleteModel(
            name='UsuarioUrl',
        ),
    ]
