# Generated by Django 4.2 on 2023-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_cpa_alter_usuario_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
