# Generated by Django 4.2.1 on 2024-09-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_uplink_usuario_up_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='userDiscord',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
