# Generated by Django 4.2.1 on 2024-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_userdiscord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isSocio',
            field=models.BooleanField(default=False),
        ),
    ]
