# Generated by Django 4.2 on 2023-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
