# Generated by Django 4.2 on 2023-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_aceptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
