# Generated by Django 4.2.1 on 2024-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_issocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
