# Generated by Django 4.2 on 2023-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_eliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoCpa',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='haveBono',
            field=models.BooleanField(default=False),
        ),
    ]
