# Generated by Django 4.2.1 on 2024-10-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idCliente',
            new_name='idSkilling',
        ),
    ]
