# Generated by Django 4.2.1 on 2024-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_idcliente_usuario_idskilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
