# Generated by Django 4.2 on 2023-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_cpaindirecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoCpaIndirecto',
            fields=[
                ('idBonoCPA', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bono', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='indirectoBono',
            field=models.BooleanField(default=False),
        ),
    ]
