# Generated by Django 4.2 on 2023-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_bonocpaindirecto_usuario_indirectobono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='indirectoBono',
            new_name='bonoIndirecto_1',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bonoIndirecto_8',
            field=models.BooleanField(default=False),
        ),
    ]
