# Generated by Django 4.2 on 2023-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rename_indirectobono_usuario_bonoindirecto_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('idSpread', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('spread', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField()),
            ],
        ),
    ]
