# Generated by Django 4.2 on 2023-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_spread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uplink',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
