# Generated by Django 4.2 on 2023-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_uplink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='monto',
            new_name='montoBonoDirecto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='montoCpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='montoIndirecto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='montoTotal',
            field=models.FloatField(default=0.0),
        ),
    ]
