# Generated by Django 4.2 on 2023-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_rename_monto_usuario_montobonodirecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='montoPagar',
            field=models.FloatField(default=0.0),
        ),
    ]
