# Generated by Django 4.2 on 2023-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_usuario_montobonoindirecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRealizado',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('afiliadoid', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.FloatField(default=0.0)),
                ('monto_pagado', models.FloatField(default=0.0)),
                ('monto_cpa', models.FloatField(default=0.0)),
                ('monto_indirecto', models.FloatField(default=0.0)),
                ('monto_bono_indirecto', models.FloatField(default=0.0)),
                ('monto_bono_directo', models.FloatField(default=0.0)),
            ],
        ),
    ]
