# Generated by Django 4.2 on 2023-08-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_pagorealizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='montoBonoDirecto',
            new_name='monto_a_pagar',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='montoBonoIndirecto',
            new_name='monto_bono_directo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='montoCpa',
            new_name='monto_bono_indirecto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='montoIndirecto',
            new_name='monto_cpa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='montoPagar',
            new_name='monto_indirecto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='montoTotal',
            new_name='monto_total',
        ),
    ]
