# Generated by Django 4.2 on 2023-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_rename_montobonodirecto_usuario_monto_a_pagar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_4',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_5',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_6',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_7',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bonoIndirecto_8',
        ),
        migrations.AddField(
            model_name='usuario',
            name='level_bono',
            field=models.IntegerField(default=0),
        ),
    ]
