# Generated by Django 4.2 on 2023-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_usuario_bonoindirecto_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='level_bono',
            new_name='level_bono_directo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='level_bono_indirecto',
            field=models.IntegerField(default=0),
        ),
    ]
