# Generated by Django 4.2 on 2023-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_rename_level_bono_usuario_level_bono_directo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monto_directo',
            field=models.FloatField(default=0.0),
        ),
    ]
