# Generated by Django 4.2.4 on 2023-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_usuario_registrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='afiliadoid',
            new_name='fpa',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='wallet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
