# Generated by Django 4.2.4 on 2023-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_rename_afiliadoid_usuario_fpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montos',
            fields=[
                ('id_monto', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('fpa', models.CharField(max_length=50)),
                ('monto_total', models.FloatField(default=0.0)),
                ('monto_a_pagar', models.FloatField(default=0.0)),
                ('monto_directo', models.FloatField(default=0.0)),
                ('monto_indirecto', models.FloatField(default=0.0)),
                ('monto_cpa', models.FloatField(default=0.0)),
                ('monto_bono_directo', models.FloatField(default=0.0)),
                ('monto_bono_indirecto', models.FloatField(default=0.0)),
                ('retiros', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='pagorealizado',
            old_name='afiliadoid',
            new_name='fpa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_a_pagar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_bono_directo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_bono_indirecto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_cpa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_directo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_indirecto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='retiros',
        ),
    ]
