# Generated by Django 4.2.4 on 2023-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_montos_rename_afiliadoid_pagorealizado_fpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpaIndirecto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='level_bono_directo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='level_bono_indirecto',
        ),
        migrations.AddField(
            model_name='montos',
            name='cpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='montos',
            name='cpaIndirecto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='montos',
            name='level_bono_directo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='montos',
            name='level_bono_indirecto',
            field=models.IntegerField(default=0),
        ),
    ]
