# Generated by Django 4.2.4 on 2023-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_rename_montos_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='haveBono',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='haveBono',
            field=models.BooleanField(default=False),
        ),
    ]
