# Generated by Django 4.2.4 on 2023-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_remove_usuario_havebono_cuenta_havebono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='haveBonoIndirecto',
            field=models.BooleanField(default=False),
        ),
    ]
