# Generated by Django 4.2.4 on 2023-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_cuenta_havebonoindirecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='haveBono',
            new_name='have_bono',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='haveBonoIndirecto',
            new_name='have_bono_indirecto',
        ),
    ]
