# Generated by Django 4.2.4 on 2023-09-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_rename_havebono_cuenta_have_bono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='monto_directo',
            new_name='cpa_directo',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='monto_indirecto',
            new_name='cpa_indirecto',
        ),
    ]
