# Generated by Django 4.2.4 on 2023-09-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_alter_cuenta_cpa_directo_alter_cuenta_cpa_indirecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoAPagar',
            fields=[
                ('id_bono', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fpa', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_indirecto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('monto_bono_directo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
