# Generated by Django 4.2.1 on 2023-09-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_bonoapagar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='cpa_directo',
            new_name='spread_directo',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='cpa_indirecto',
            new_name='spread_indirecto',
        ),
    ]
