# Generated by Django 4.2.1 on 2023-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_rename_cpa_directo_cuenta_spread_directo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('cpa', models.FloatField(max_length=50)),
            ],
        ),
    ]
