# Generated by Django 4.2.1 on 2023-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_cpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpa',
            name='cpa',
            field=models.FloatField(),
        ),
    ]
