# Generated by Django 4.2.1 on 2024-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_alter_cpa_cpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('idBroker', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('broker', models.CharField(max_length=50)),
            ],
        ),
    ]
