# Generated by Django 4.2.1 on 2024-09-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_alter_cpa_cpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonoAPagar',
        ),
        migrations.DeleteModel(
            name='BonoCpa',
        ),
        migrations.DeleteModel(
            name='BonoCpaIndirecto',
        ),
        migrations.DeleteModel(
            name='CPA',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='PagoRealizado',
        ),
        migrations.DeleteModel(
            name='Spread',
        ),
    ]
