# Generated by Django 4.2.1 on 2024-01-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='broker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.broker'),
            preserve_default=False,
        ),
    ]
