# Generated by Django 4.2.1 on 2024-09-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_roles_servicios_remove_usuario_roles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referidos',
            new_name='Referido',
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Rol',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Servicio',
        ),
    ]
