# Generated by Django 4.2.1 on 2024-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_usuario_broker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_bingx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fpa_bingx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fpa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
