# Generated by Django 4.2.1 on 2024-01-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_usuario_codigo_bingx_usuario_fpa_bingx_usuario_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='broker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.broker'),
        ),
    ]
