# Generated by Django 4.2 on 2023-04-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Afiliado',
        ),
        migrations.RenameField(
            model_name='afiliado',
            old_name='idCliente',
            new_name='idAfiliado',
        ),
    ]
