# Generated by Django 4.2 on 2023-04-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0004_cliente_usertelegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comprobante',
        ),
    ]
