# Generated by Django 4.2 on 2023-04-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0005_remove_cliente_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='telefono',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
