# Generated by Django 4.1.7 on 2023-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0007_afiliado_referenciaafiliado_cliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
