# Generated by Django 4.2.4 on 2023-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0008_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='idAfiliado',
            new_name='fpa',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='referenciaAfiliado',
        ),
        migrations.RemoveField(
            model_name='afiliado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='upline',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
