# Generated by Django 4.2.1 on 2023-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0009_rename_idafiliado_afiliado_fpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='url_video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
