# Generated by Django 4.2.7 on 2024-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0010_afiliado_url_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='url_video',
            field=models.URLField(default='https://www.youtube.com/watch?v=HgKjhFEguy'),
        ),
    ]
